---
title: "NA handling"
author: "DSjayjang"
date: "2024-04-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **※ NA handling (결측치 처리)**

◎ 사용할 패키지: tidyverse
```{r message=FALSE, warning=FALSE}
library(tidyverse)
```

<br>

◎ Data 생성
```{r}
df <- data.frame(name = c('Hwayoung',	NA,	'Sua',	'Sojin',	'Minjeong',	'Gaeun',	'Janghoon',	'Sunghoon',	'Jaeyoung',	'Yeseung',	'Jungjae',	'Kyunghwan'),
                   class = c(1, 2, 3, 2, 3, 1, 1, 2, 3, 3, 2, 2),
                   math = c(74, 56, NA, 57, 42, 39, 55, 68, NA, 83, 92, 71),
                   eng = c(76, 70, 77, 68, NA, 63, 70, NA, 95, NA, 100, 65))
df2 <- data.frame(df, 
                   gender = c('f', NA, NA, NA, NA, NA, 'm', NA, NA, NA, NA, NA))
```

<br>

◎ 예시 Data (df)
```{r}
df; df2
```

<br>
<br>

## ■ NA 여부 체크
### □ **anyNA**이용

```{r}
anyNA(df)
```

### □ **is.na **이용

```{r}
is.na(df)
```

### □ **table **이용
Data에 NA가 몇개 있는지 (TRUE 값)

```{r}
table(is.na(df))
```

### □ **colSums **이용
각 컬럼별 NA 개수 보기

```{r}
colSums(is.na(df))
```

<br>
<br>

## ■ NA 제거
### □ na.omit
NA가 포함된 모든 Data를 지울 수 있지만, 너무 많은 Data가 삭제될 수 있음
```{r}
na.omit(df2)
```

<br>

### □ `tidyverse` 패키지 이용
#### ◎ **filter**
```{r}
# 수학 점수가 NA인 경우
df %>%
  filter(is.na(math))
```

```{r}
# 수학 점수가 NA가 아닌 경우
df %>%
  filter(!is.na(math))
```

```{r}
# 수학과 영어 점수가 NA가 아닌 경우
df %>%
  filter(!is.na(math) & !is.na(eng))
```

<br>

#### ◎ **drop_na**
```{r}
df %>%
  drop_na()
```

```{r}
df %>%
  drop_na(math)

df %>%
  drop_na(math,eng)
```


```{r}
#NA를 제거한 Data의 수학과 영어 평균점수
df2 %>%
  drop_na(math, eng) %>%
  group_by(class) %>%
  summarize(mean(math), mean(eng))
```

<br>

#### ◎ **na.rm**
```{r}
df2 %>%
  summarize(mean(math, na.rm=T))
```


<br>
<br>

## ■ NA 대체
### □ **fill **함수 이용
바로 위에 있는 값들로 채움
```{r}
df2 %>%
  fill(math)
```

```{r}
df2 %>%
  fill(gender, .direction = "down")
```

<br>

### □ **replace_na **이용 
```{r}
#NA를 0값으로 대체
df2 %>%
  replace_na(list(math = 0))
```

```{r}
#수학은 0점, 영어는 10점으로 대체
df2 %>%
  replace_na(list(math = 0, eng = 10))
```

```{r}
# NA값을 수학평균점수로 대체
# mean에 $로 컬럼명 지정해야함
df2 %>%
  replace_na(list(math = mean(df2$math, na.rm = T)))
```
<br>

### □ **mutate **이용
```{r}
# NA값을 수학평균점수로 대체
df2 %>%
  mutate(math = ifelse(is.na(math), mean(math, na.rm = T), math))
```
